### ISSUE TITLE
Trouble with own skill

### ISSUE THREAD

**Issue by JacoboRG12** [FurhatRobotics/example-skills#39]
Hi, I'm doing my own skill that consists in a simple game of questions. Now I'm making the introduction, but I'm having problems with the flow between states in the robot, but in the SDK all works perfect.
The states are the following: Init --> Puente --> Greetings
![image](https://user-images.githubusercontent.com/81679718/233692825-eb8ae17f-04f6-4453-9063-a6c2d699b0e1.png)
![image](https://user-images.githubusercontent.com/81679718/233692896-7008f66d-43bf-4ec5-807f-ef1ff7a65233.png)
![image](https://user-images.githubusercontent.com/81679718/233692965-362b832d-1ce3-45ac-b333-1007f12204c3.png)
The problem is when I get to the state Puente, that should take me to Greeting, but instead of this, it takes me to Idle and I don´t know why, because in the the SDK all works correctly, but with the robot this does not happen.
I cannot attach the code, so I hope that images could serve you
Thanks and greetings

**Comment by JacoboRG12** [comment]
Idle state
![image](https://user-images.githubusercontent.com/81679718/233694497-d18fed5b-7096-4b7e-9454-b20d3722c876.png)

**Comment by alexbainbridge** [comment]
You may find that the Furhat slack (skills channel) is the place to ask questions about your own Furhat Skills. See info base of here how to get an invite https://docs.furhat.io/robot/#community-slack-channel

**Comment by MathieuRH** [comment]
Hey Jacobo ! 
This is indeed the kind of question that you belong in the open community slack ^^
That said, your problem is pretty simple, you should change the furhat.ask() to a furhat.say() in your Puente state. A furhat.ask() will  never execute the code behind it since it interrupts the flow to wait for an response (see [our docs documentation](https://docs.furhat.io/listening/#asking)).
I will be closing this ticket since it does not really belong here, but feel free to open another skill conversation in the slack community if needed.
